/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117899-g3c3bf6c109-20241125"
#endif /* AVUTIL_FFVERSION_H */
